# Contenu du fichier 'compose.yaml'

---
services:

  srv-web:
    image: nginx:latest
    networks:
      - backend
      - frontend
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./efcs_site/html:/usr/share/nginx/html
      - ./efcs_site/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./efcs_site/conf/nginx.conf:/etc/nginx/nginx.conf

  php:
    image: php:8.3-fpm-alpine
    networks:
      - backend
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      #- DB_USER_NAME: $_ENV["DB_USER_NAME"]
      #- DB_USER_PASS: $_ENV["DB_USER_PASS"]
    ports:
      - '9000:9000'
    volumes:
      - ./efcs_site/html:/usr/share/nginx/html

  mysql:
    image: mysql:latest
    #build: './mysql/'
    restart: always
    environment:
      #MYSQL_ROOT_PASSWORD: my_efcs_root_password
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - net_data
    ports:
      - '3306:3306'
    volumes:
      - mysql_db_storage:/var/lib/mysql

  volumes:
    - mysql_db_storage

  networks:
    backend:
    frontend:
    net_data:
