# Contenu du fichier 'compose.yaml'

---
services:

  srv-web:
    image: nginx:latest
    networks:
      - backend
      - frontend
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./efcs_site/html:/usr/share/nginx/html
      - ./efcs_site/conf:/etc/nginx/conf.d
      #- ./efcs_site/conf/default.conf:/etc/nginx/conf.d/default.conf
      #- ./efcs_site/conf/nginx.conf:/etc/nginx/nginx.conf

  php:
    #image: php:8.3-fpm-alpine
    build: './php/'
    networks:
      - backend
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      #- DB_USER_NAME: $_ENV["DB_USER_NAME"]
      #- DB_USER_PASS: $_ENV["DB_USER_PASS"]
    ports:
      - '9000:9000'
    volumes:
      - ./efcs_site/html:/usr/share/nginx/html

  mysql:
    image: mysql:latest
    #build: './mysql/'
    restart: always
    environment:
      #MYSQL_ROOT_PASSWORD: my_efcs_root_password
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - backend # Même networks que Nginx et PHP
    ports:
      - '3306:3306'
    volumes:
      - mysql_db_storage:/var/lib/mysql

networks:
  backend:
  frontend:

volumes:
  mysql_db_storage:
