# Playbook : deploy.yaml

# Contenu du fichier 

---
- name: "NGinx, PHP et MySqL installation avec Docker"
  hosts: prod
  pre_tasks:
    - name: INSTALLER LES DEPENDANCES DOCKER
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      tags: docker

    - name: AJOUT CLE GPG DE DOCKER
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: docker

    - name: AJOUT DEPOT APT DE DOCKER
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
      tags: docker

    - name: INSTALLER DOCKER
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags: docker

    - name: DEMARRE DOCKER
      ansible.builtin.systemd_service:
        state: started
        name: docker
      tags: docker
