# Playbook : deploy.yaml

# Contenu du fichier 

---
- name: "NGinx, PHP et MySqL installation avec Docker"
  hosts: Web
  become: true
  vars:
    ansible_sudo_pass: "egeorges*1"
  tasks:
    - name: INSTALLER LES DEPENDANCES DOCKER
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      tags: docker-dep

    - name: AJOUT CLE GPG DE DOCKER
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: docker-dep

    - name: AJOUT DEPOT APT DE DOCKER
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
      tags: docker-dep

    - name: INSTALL DOCKER / DOCKER-COMPOSE
      apt:
        name:
          - docker-ce
          - docker-compose-plugin
        state: present
        update_cache: yes
      tags: docker-ins

    - name: DEMARRER DOCKER
      ansible.builtin.systemd_service:
        state: started
        name: docker
      tags: docker-str
